#!/bin/bash -  
  
function mytest2()  
{  
    echo "mytest2"  
    echo "args $1"  
    test=$1  
    test1=$1
    return 0  
}  
  
mytest2 1  
echo "return $?"  
echo "g_var=$test"
echo "test1=$test1"
